### ISSUE TITLE
Lock expiration is ambiguous in the API documentation

### ISSUE THREAD

**Issue by qyjyork** [automata-tech/eva_python_sdk#47]
Hi,
I have a question about the 'lock' status.
According to the API documentation (https://automata.tech/docs/v/3.1.0/), in the Section 'controls->lock->locking' it says 'Note that the lock will expire after 60 seconds if not renewed.'.
However, in the section 'overview->run modes', it says that the lock has to be renewed every 5 seconds in teach mode while 5 minutes in automatic mode.
So there seems to be a conflict between these two statements.
Would you help me clarify it? 
Really appreciate for your help.

**Comment by LouisBrunner** [comment]
Hi @qyjyork,

Thank you for this issue!

As you have highlighted, the [Controls > Lock](https://automata.tech/docs/v/3.1.0/api/controls/#locking) section is a bit outdated and doesn't mention the [Run Modes](https://automata.tech/docs/v/3.1.0/api/overview/#run-modes) or the right timeout. The second one is the correct: lock timeout is dependent on *Run Modes*, the lock will expire after 5 seconds in _teach mode_ and 5 minutes in _automatic mode_.

We will update the documentation, unfortunately due to our deployment method the change will only be reflected after the next update.

**Comment by qyjyork** [comment]
thanks!!!

**Comment by LouisBrunner** [comment]
The documentation has since been updated (3.2.0, 4.0.0 and 4.1.0), https://automata.tech/docs/v/4.1.0/api/controls/#locking
